### ISSUE TITLE
Criar projeto inicial (códigos iniciais)

### ISSUE THREAD

**Issue by gbaierski** [gbaierski/hourganize#5]
Deve ser criado o projeto em si. 

Devem ser criadas as pastas básicas e organizada a arquitetura base do sistema.

**Comment by ViniciusAcordiSoethe** [comment]
Feito Primeiro passo da codagem , Criado o vue na versão 3.2.37 usando Single page Application , e Pinia

**Comment by ViniciusAcordiSoethe** [comment]
Corrigido o meu commit  que foi feito como Verme usando o comando 

git rebase -i --root -x "git commit --amend --author='YOUR_USERNAME <user@example.com> --no-edit'"
