### ISSUE TITLE
Desenvolver Seleção de Perfil

### ISSUE THREAD

**Issue by ViniciusAcordiSoethe** [gbaierski/hourganize#7]
Desenvolver uma tela de seleção de Perfil, no components, mome do arquivo

**Comment by ViniciusAcordiSoethe** [comment]
Feito a o componet de login e view da seleção de perfil

**Comment by ViniciusAcordiSoethe** [comment]
![image](https://user-images.githubusercontent.com/29065500/177590906-b6150247-e751-491d-9a77-59932a19535f.png)

O padrão que eu defini para a componentisação foi o de usar `:to"{name: 'NomeDaRouta'}"`

assim podesse alterar o caminho apos sem maiores problemas 

![image](https://user-images.githubusercontent.com/29065500/177591271-bf678642-d9da-4234-8bbb-9b093782787a.png)

**Comment by gbaierski** [comment]
**Code Review:**

@ViniciusAcordiSoethe 
https://github.com/gbaierski/hourganize/commit/365003cda2011755e349ed9a9b4ad0a7064f9bff#r77916885

**Comment by gbaierski** [comment]
@ViniciusAcordiSoethe 

Sobre esse desenvolvimento, você já quis fazer a componentização da tela?

Eu acabei não explicando direito. A ideia é que você faça a tela "bruta" e eu aplico a componentização. Ou seja, você desenvolve o layout inteiro e eu separo os componentes.
