### ISSUE TITLE
Criar a logo do projeto

### ISSUE THREAD

**Issue by gbaierski** [gbaierski/hourganize#9]
Deve ser feito o design da logo com base no que foi decidido na issue #3

**Comment by gbaierski** [comment]
**Desenvolvimento:**
![hourganize](https://user-images.githubusercontent.com/32649340/177690250-3d820424-6188-4803-80e8-bebb6f666614.png)
![hourganizeW](https://user-images.githubusercontent.com/32649340/177690257-940a6dd4-e08e-4b85-9f96-dc30ec5b66af.png)
![hourganize](https://user-images.githubusercontent.com/32649340/177690258-9a55d905-7905-4fc2-a882-d024f7aac2af.jpg)

**Comment by ViniciusAcordiSoethe** [comment]
Ficou dentro dos padrões pedidos e não apenas isso transcendeu os limites da imaginação e beleza 

https://github.com/gbaierski/hourganize/commit/021dabfc955efb8f6fb5a8b35389c6f17da9d433#r77981872
